# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eeef4a9df836c5e3d287405c83226f60bb3c6508ed465675678e83d9fb7738ea82e272933f62ce68afa8cdbffd020a4802f53257665cc6b9ac74be1b416815a

test:
  secret_key_base: 2e081d6c020011387d1a74bc76794149add95f8bf5a46152f5aa8ee792b66d4104b25252b802e8b76fe8d6fa7c2d31f208b843fadd35dc06d4fb3577fcbe7815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
